# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  companyzapi:
    image: companyzapi
    build:
      context: .
      dockerfile: src/CompanyZ.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5020:5020
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
